schools/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from schools.views import *

urlpatterns = patterns('')

utils/urls.py
from django.conf.urls import patterns, url

from .views import set_session
from klprestApi.views.HomeApi import Home

urlpatterns = patterns('',
    url(r'^home/$', Home(), name='home'),
    url(r'^set/session/$', set_session, name='set_session')
)

schools/models.py
import datetime

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from django.db import connection
from django.db.models.signals import post_save, pre_save
from schools.receivers import KLP_NewInst_Permission

from object_permissions import register
from fullhistory import register_model

# Table Structure For Klp

register_model(User)

primary_field_type = [(0, 'Default'),
                      (1, 'Integer'),
                      (2, 'Char'),
                      (3, 'Date'),
                      (4, 'Lookup')]

active_status = [
    (0, 'Deleted'),
    (1, 'Inactive'),
    (2, 'Active'),
    (3, 'Promoted'),
    (4, 'Promotion Failed'),
    (5, 'Passed Out'),
    (6, 'Detained'),
    (7, 'Completed'), ]

INSTITUTION_GENDER = [('boys', 'boys'), ('girls', 'girls'), ('co-ed',
                      'co-ed')]

GENDER = [('male', 'male'), ('female', 'female')]

Group_Type = [('Class', 'Class'), ('Center', 'Center')]

QuestionType = [(1, 'Marks'), (2, 'Grade')]

RELATION_TYPE = [('Mother', 'Mother'),
                 ('Father', 'Father'),
                 ('Siblings', 'Siblings')]

Assessment_type = [(1, 'Institution'), (2, 'Student Group'), (3,
                   'Student')]

alpha_list = [('', 'No Section')]
A_ASCII = 65
Z_ASCII = 90
[alpha_list.append((chr(each), chr(each))) for each in range(A_ASCII, Z_ASCII+1)]


class Institution_Category(models.Model):

    '''This Class stores the Institution Category Information'''

    name = models.CharField(max_length=50)
    category_type = models.IntegerField()

    def __unicode__(self):
        return '%s' % self.name


register_model(Institution_Category)


class Moi_Type(models.Model):

    '''This Class stores the Mother Toungue (Languages) Information'''

    name = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.name


register_model(Moi_Type)


class Institution_Management(models.Model):

    '''This Class stores the Institution Management Information'''

    name = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.name


register_model(Institution_Management)  # Register model for to store information in fullhistory


class Institution_address(models.Model):

    ''' This class stores information about institution address '''

    address = models.CharField(max_length=1000)
    area = models.CharField(max_length=200, blank=True, null=True)
    pincode = models.CharField(max_length=100, blank=True, null=True)
    landmark = models.CharField(max_length=1000, blank=True, null=True,
                                help_text='Can be comma separated')
    instidentification = \
        models.CharField(max_length=1000, blank=True,
                         null=True,
                         help_text='Can be comma separated')
    instidentification2 = \
        models.CharField(max_length=1000, blank=True,
                         null=True,
                         help_text='Can be comma separated')
    route_information = \
        models.CharField(max_length=500, blank=True,
                         null=True,
                         help_text='Can be comma separated')


register_model(Institution_address)  # Register model for to store information in fullhistory


class Boundary_Category(models.Model):

    '''This Class stores the Boundary Category Information'''

    boundary_category = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s' % self.boundary_category


register_model(Boundary_Category)  # Register model for to store information in fullhistory


class Boundary_Type(models.Model):

    '''This Class stores the Boundary Type Information'''

    boundary_type = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s' % self.boundary_type


register_model(Boundary_Type)  # Register model for to store information in fullhistory


class Staff_Type(models.Model):

    '''This Class stores information about Staff Type'''

    staff_type = models.CharField(max_length=100)
    category_type = models.IntegerField()

    def __unicode__(self):
        return '%s' % self.staff_type


register_model(Staff_Type)  # Register model for to store information in fullhistory


class Staff_Qualifications(models.Model):

    ''' This Class Stores Information about staff qualification '''

    qualification = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s' % self.qualification


register_model(Staff_Qualifications)  # Register model for to store information in fullhistory


class Boundary(models.Model):

    '''This class specifies the longitude and latitute of the area'''

    parent = models.ForeignKey('self', blank=True, null=True)
    name = models.CharField(max_length=300)
    boundary_category = models.ForeignKey(Boundary_Category,
                                          blank=True, null=True)
    boundary_type = models.ForeignKey(Boundary_Type, blank=True,
                                      null=True)
    active = models.IntegerField(blank=True, null=True, default=2)

    class Meta:

        """ Used For ordering """

        ordering = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def getChild(self, boundaryType):
        if Boundary.objects.filter(parent__id=self.id, active=2,
                                   boundary_type=boundaryType).count():
            return True
        elif Institution.objects.filter(boundary__id=self.id,
                                        active=2).count():
            return True
        else:
            return False

    def getModuleName(self):
        return 'boundary'

    def getViewUrl(self, boundaryType):
        return '<a href="/boundary/%s/%s/view/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="Boundary" /> &nbsp; <span id="boundary_%s_text">%s</span> </a>' \
            % (self.id, boundaryType, self.name, self.id, self.name)

    def CreateNewFolder(self, boundaryType):
        return '<span><a href="/boundary/%s/%s/view/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="Boundary" /> &nbsp; <span id="boundary_%s_text">%s</span> </a></span>' \
            % (self.id, boundaryType, self.name, self.id, self.name)

    def get_view_url(self, boundaryType):
        return '/boundary/%s/%s/view/' % (self.id, boundaryType)

    def get_edit_url(self):
        return '/boundary/%s/update/' % self.id

    def get_update_url(self):
        return '/boundary/%d/update/' % self.id

    def getPermissionChild(self, boundaryType):
        if Boundary.objects.filter(parent__id=self.id, active=2,
                                   boundary_type=boundaryType):
            return True
        else:
            return False

    def getPermissionViewUrl(self):
        return '<a href="/boundary/%s/permissions/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
            % (self.id, self.name, self.name)

    def getAssessmentPermissionViewUrl(self, assessment_id):
        return '<a href="/boundary/%s/assessmentpermissions/%s/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
            % (self.id, assessment_id, self.name, self.name)

    def showPermissionViewUrl(self, userSel):
        if self.boundary_category.id in [9, 10, 13, 14]:
            return '<a href="/show/%s/user/%s/permissions/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
                % (self.id, userSel, self.name, self.name)
        else:
            return '<a href="/list/%s/user/%s/permissions/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
                % (self.id, userSel, self.name, self.name)


register_model(Boundary)


class Institution(models.Model):

    ''' It stores the all data regarding Institutions'''

    boundary = models.ForeignKey(Boundary)
    dise_code = models.CharField(max_length=14, blank=True, null=True)
    name = models.CharField(max_length=300)
    cat = models.ForeignKey(Institution_Category, blank=True, null=True)
    institution_gender = \
        models.CharField(max_length=10,
                         choices=INSTITUTION_GENDER, default='co-ed')
    languages = models.ManyToManyField(Moi_Type)
    mgmt = models.ForeignKey(Institution_Management, default='ed')
    inst_address = models.ForeignKey(Institution_address, blank=True,
                                     null=True)
    active = models.IntegerField(blank=True, null=True, default=2)

    class Meta:

        ordering = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def get_all_cat(self, category_type):
        return Institution_Category.objects.all(category_type=category_type)

    def getChild(self):
        if StudentGroup.objects.filter(institution__id=self.id,
                                       active=2).count():
            return True
        else:
            return False

    def get_all_mgmt(self):
        return Institution_Management.objects.all()

    def get_all_languages(self):
        return Moi_Type.objects.all()

    def getModuleName(self):
        return 'institution'

    def get_update_url(self):
        return '/institution/%d/update/' % self.id

    def getViewUrl(self):

klprestApi/views/AllidsActivate.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""

Institution Api is used
1) To view Individual Institution details.
2) To create new Institution
3) To update existing Institution
4) To list boundaries/institutions while assign permissions
"""
import simplejson

from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from schools.models import Boundary, Institution, Programme, Assessment,\
    Question, StudentGroup, Student, Staff, Student_StudentGroupRelation,\
    current_academic


def KLP_act_form(request):
    ''' To show the admin form for activate the records '''

    # get logged in user

    user = request.user
    if user.is_anonymous():
        return HttpResponseRedirect('/login/')
    else:

        context = {'title': 'Karnataka Learning Partnership ',
                   'user': user}
        return render(request,
                      'viewtemplates/AllidsActivate.html',
                      context)


@csrf_exempt
def KLP_Activation(request):
    """ To actiave the records>"""

    isExecute = True

    selCategoryTyp = request.POST.get('form-staging-modelname')
    selCategoryids = request.POST.get('form-staging-allids')

    if selCategoryids is None:
        isExecute = False
        resStr = 'Please give atleast one id'
    else:
        isExecute = False
        allids1 = selCategoryids.split(',')
        model_name1 = selCategoryTyp
        respDict = {'respStr': selCategoryTyp, 'isExecute': isExecute}

        actiontype = int(request.POST.get('form-staging-action'))
        allids = []
        for k in allids1:
            allids.append(int(k))
        modelDict = {
            'boundary': Boundary,
            'institution': Institution,
            'programme': Programme,
            'assessment': Assessment,
            'question': Question,
            'studentgroup': StudentGroup,
            'student': Student,
            'staff': Staff,
            'class': StudentGroup,
            'center': StudentGroup,
        }
        if model_name1 != 'student':
            obj1 = \
                modelDict[model_name1].objects.filter(id__in=allids,
                                                      active=int(actiontype))
            obj3 = modelDict[model_name1].objects.filter(id__in=allids)
        else:
            obj1 = \
                modelDict[model_name1].objects.filter(child__id__in=allids,
                                                      active=int(actiontype))
            obj3 = \
                modelDict[model_name1].objects.filter(child__id__in=allids)
        actiondic = {1: 'Deactivated', 2: 'Activated'}

        if len(obj3) == 0 or len(obj3) != len(allids):
            idslist3 = obj3.values_list('id')
            idlist4 = []
            for k in idslist3:
                idlist4.append(k[0])
            resStr = obj1.model._meta.module_name + ' Ids ' \
                + ','.join(str(v) for v in allids if v not in idlist4) \
                + ' are not exist .Please verify the ids .'
        elif len(obj1) != 0:

            idlist1 = obj1.values_list('id')
            resStr = obj1.model._meta.module_name + ' Ids ' \
                + ','.join(str(v1[0]) for v1 in idlist1) \
                + ' are already ' + actiondic[actiontype] \
                + ' .Please verify the ids.'
        else:

            if actiontype == 1 and model_name1 != 'student' and model_name1 != 'assessment':
                childlength = hasChildObj(allids, model_name1)
            else:
                childlength = []
            if model_name1.lower() == 'student' and actiontype == 1 and model_name1 != 'assessment':
                childi = obj3.values_list('id', flat=True)
                relObjects = \
                    Student_StudentGroupRelation.objects.filter(student__id__in=
                                                                childi,
                                                                academic=
                                                                current_academic,
                                                                active=2)
                relObjects.update(active=1)
                childlength = []
            if len(childlength) == 0:
                obj2 = obj3
                isExecute = True
                idlist2 = obj2.values_list('id')
                idstr = ','.join(str(v1[0]) for v1 in idlist2)
                obj2.update(active=actiontype)

                SendingMail(idstr, obj2.model._meta.module_name,
                            actiondic[actiontype])
                receiver = settings.REPORTMAIL_RECEIVER
                receiver = ','.join(str(v1) for v1 in receiver)
                if not actiondic[actiontype] == "Deactivated":
                    message = \
                        'A mail will be sent to %s as soon as all the \
                        records are activated .' \
                        % receiver
                else:
                    message = \
                        'A mail will be sent to %s as soon as all the \
                        records are deactivated .' \
                        % receiver
                resStr = obj2.model._meta.module_name + ' Ids ' + idstr \
                    + ' are Successfully ' + actiondic[actiontype] \
                    + ' .' + message
            else:
                idstr = ','.join(str(v1) for v1 in childlength)
                resStr = model_name1 + ' Ids ' + idstr \
                    + ' are having child objects.So can not delete it.\
                    First Deactivate the child objects,then try to deactivate'
    respDict = {'respStr': resStr, 'isExecute': isExecute}

    return HttpResponse(simplejson.dumps(respDict),
                        content_type='application/json; charset=utf-8')


def hasChildObj(idlists, model_name1):
    modelDict = {
        'boundary': Boundary,
        'institution': Institution,
        'programme': Programme,
        'assessment': Assessment,
        'question': Question,
        'studentgroup': StudentGroup,
        'student': Student,
        'staff': Staff,
        'class': StudentGroup,
        'center': StudentGroup,
    }

        # Checking user Permissions

    haschildlist = []
    for k in idlists:

          # Get Object based on id and model to delete

        obj = modelDict[model_name1.lower()].objects.get(pk=k)
        if model_name1.lower() == 'boundary':
            flag = obj.getChild(obj.boundary_type)
        elif model_name1.lower() in ['class', 'studentgroup']:
            if Student_StudentGroupRelation.objects.filter(
                student_group__id=k, active=2,
                    academic=current_academic()).count():
                flag = True
            else:
                flag = False
        else:
            flag = obj.getChild()

        if flag:
            haschildlist.append(str(k))

    return haschildlist


def SendingMail(idlist, mname, atype):
    inst_liststr = idlist
    sender = settings.REPORTMAIL_SENDER
    receiver = settings.REPORTMAIL_RECEIVER
    if atype == "Deactivated":
        subject = 'Deactivated list'
        fullmsg = 'Following %s Ids are Deactivated  :  \n %s ' % (mname, inst_liststr)
    else:
        subject = 'Activated list'
        fullmsg = 'Following %s Ids are Activated  :  \n %s ' % (mname, inst_liststr)
    send_mail(subject, fullmsg, sender, receiver)

schools/templates/viewtemplates/assessment_lookup_copy.html
{% load template_tags %}

<div class="KLP_Button_Header">
	<!-- This Block shows the buttons for add, edit and delete-->
	
	<span class="KLP_Sub">
                <a class="KLP_Button"  href="/assessment/{{assessment_id}}/view/" onclick="KLP_View(this);">View Assessement</a>
        </span>
		<span  style="display:none" id="viewlookup" class="KLP_Sub" >
                <a class="KLP_Button" id="lookuplist" href="/assessment/assessment_lookup/{{assessment_id}}/view" onclick="return KLP_View(this);">View Lookup Value</a>
    </span>
		
</div>

<div class="detailHead">
<span class="hedText">Copy The Lookup Value </span>
<span id ="showsuccess" style="display:none;" class="klp_MsgTxt"></span>
</div>

<form action="." method="POST" class="niceform" name="name_copyassessmentLooupDetail" id="id_copyassessmentLooupDetail">

<div>
	From Assessment</th> 
   
    	<!-- Child Information -->
		 
		  <select id="lookupValues" name="lookupValues">
		 {% for assessment in assessmentList %}
		 <option value="{{assessment.id}}">{{assessment.programme.name}}-->{{assessment.name}}</option>
    
			
	   {% endfor %}
	</select>
	
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" name="save" id="id_save" value="Copy" tabindex=4 />
      

<div>



</div>

</form>

<script>
$(document).ready(function(){
$("#id_save").click(function(){

    	 
	

$.ajax({
      type: "POST",
      url:"/assessment/assessment_lookup/{{assessment_id}}/copy",
      data: $("#id_copyassessmentLooupDetail").serialize(),
      
      
	  success:function(data){
			
		    
			 
                    if (data == 'Copied Successfully'){
			
			
			
			$('#lookuplist').trigger('onclick');
			$("#successMsgHead").show();
			$("#copiedstatus").html(data);
		
		}
		else{
			
		   $('#failureMsgHead').show();
		   successObj.hide();
		}
		
	 
	  }
});
		
		return false;
		
   
	
});	
});	

</script>
</div>

schools/templates/viewtemplates/child_detail.html
{% load template_tags %}
<tr id="student_{{child.id}}">
	<td  class="tot-border1">{{child.first_name}}<input type="hidden" id="success_status" size="15" value="True" / ></td>
	<td  class="tot-border1">{{child.last_name}}</td>
	<td  class="tot-border1">{{child.dob|date:"d M Y"}}</td>
	<td  class="tot-border1">{{child.mt}} </td>
	<td  class="tot-border1">{{child.gender}}</td>
	<td  class="tot-border1">{% if child.getMother.first_name %}Mother: {{child.getMother.first_name}} <br />{% endif %} {% if child.getFather.first_name%}Father: {{child.getFather.first_name}}{% endif %}</td> 
        <td  class="tot-border2"><input type="checkbox" value = "{{child.id}}" name="students" onchange="updateEditUrl()"/></td>
		
</tr>

schools/templates/viewtemplates/institution_form.html
{% load crispy_forms_tags %}
{% load template_tags %}
<div class="detailHead">
    <span class="hedText">{{extra_context|displayValue:'institutionType'}} Form</span>
</div>

<form action="." method="POST" enctype="multipart/form-data" id="institutionForm" onsubmit="return false;">
    {% crispy form helper %}
    <input type="hidden" name="url" value="/boundary/{{extra_context|displayValue:'referKey'}}/institution/creator/" id="url" />
    <input type="hidden" name="form-buttonType" id="id_form-buttonType" value="save" />
    <input type="hidden" id="institution_id" size="15" value="{{extra_context|displayValue:'prevousId'}}" / >
    <input type="hidden" id="success_status" size="15" value="{{extra_context|displayValue:'showsuccess'}}" / >

    <div class="form-actions">
        <input type="submit" name="submit" value="Save" class="btn btn-primary" id="id_save">
        <input type="submit" name="save_and_create" id="id_save_and_create" value="Save And Create Another" class="btn btn-primary">
    </div>
</form>


<script>
$(document).ready(function(){


   $("#id_save").click(function(){
    /* Clicking on save button hide all prv msgs and call form submit and pass button type is save */
    KLP_Hide_Msg();
    parentVal = $("#id_boundary").val();
    $("#id_form-buttonType").val('save');
    KLP_form_submit(parentVal);

   });

   $("#id_save_and_continue").click(function(){
    /* Clicking on save and continue button hide all prv msgs and call form submit and pass button type is save and continue */
    KLP_Hide_Msg();
    $("#id_form-buttonType").val('save and continue');
    parentVal = $("#id_boundary").val();
    KLP_form_submit(parentVal);
   });

   $("#id_save_and_create").click(function(){
    /* Clicking on save and add another button hide all prv msgs and call form submit and pass button type is save and add another */
    KLP_Hide_Msg();
    parentVal = $("#id_boundary").val();
    $("#id_form-buttonType").val('save and add another');
    KLP_form_submit(parentVal, 'id_boundary');


   });


   var KLP_form_submit = function(parentVal, parentId){
    /* post data using post method */
    $.post(
            $('#url').val(),
            $("#institutionForm").serialize(),
                function(data){
                     /* Get Response */
                    $("#dyncData").html(data);
                    // NFInit();
                    $('input:visible:enabled:first').focus();
                    var successStatus = $("#success_status").val();
                    if (successStatus == 'True'){
                        /* If It success show success msg and create new node in tree */
                        $("#successMsgHead").show();
                $("#klp_MsgTxt").html("{{extra_context|displayValue:'institutionType'}} Created Successfully")
                        if (parentId != null)
                            $("#"+parentId).val(parentVal);
                        ObjId='#boundary_'+parentVal
                        Obj=$(ObjId)
                        KLP_Create_Node(Obj,'institution');
                    }
               }
           );
   }

});
</script>

schools/templates/viewtemplates/student_replaceform.html
{% load template_tags %}
<form action="." method="POST" enctype="multipart/form-data" id="studentForm" onsubmit="return false;" class="niceform">{% csrf_token %}
                            <input type="hidden" name="url" value="/studentgroup/{{extra_context|displayValue:'referKey'}}/student/creator/" id="url" />    
                            <input type="hidden" name="parentId" value="{{extra_context|displayValue:'referKey'}}" id="parentId" />
                            <input type="hidden" name="form-buttonType" id="id_form-buttonType" value="save" />
			    <input type="hidden" id="success_status" size="15" value="{{extra_context|displayValue:'showsuccess'}}" / >
			    <table class="tblprofile">
                            {% with form|first as childForm %}
				{{childForm.management_form}}
				{% with childForm.forms|first as entryForm %}
				<tr>
				    <td><label class="KLP_required">First Name:</label></td>
				    <td>
					{{entryForm.first_name}}
				    </td>
				    <td>
                                    	{% for error in entryForm.first_name.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				</tr>
				<tr>
				    <td><label class="KLP_required">Last Name:</label></td>
				    <td>
					{{entryForm.last_name}}
				    </td>
				    <td>
                                    	{% for error in entryForm.last_name.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				</tr>
				<tr>
				    <td><label for="address">Date of Birth:</label></td>
				    <td>
					{{entryForm.dob}}
				    </td>
				</tr>
				<tr>
				    <td><label class="KLP_required">Gender:</label></td>
				    <td>
					{{entryForm.gender}}
				    </td>
				    <td>
                                    	{% for error in entryForm.gender.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				</tr>
				<tr>
				    <td><label class="KLP_required">Mother Tounge:</label></td>
				    <td>
					{{entryForm.mt}}<input type="hidden" name="form-0-relations" id="id_relations" size="15" value=""/>
				    </td>
				    <td>
                                    	{% for error in entryForm.mt.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				</tr>
				{% endwith %}
			    {% endwith %}
				<tr>
				    <td><label class="KLP_required">Mother Name:</label></td>
				    <td>
					<input type="text" name="form-0-mother" id="id_mother" size="15" value=""/>
				    </td>
				    <td>
                                    	{% for error in entryForm.mother.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				</tr>
				<tr>
				    <td><label class="KLP_required">Father Name:</label></td>
				    <td>
					<input type="text" name="form-0-father" id="id_father" size="15" value=""/>
				    </td>
				    <td>
                                    	{% for error in entryForm.father.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				</tr>
    			    
    			    {% with form|last as studentForm %}
				{{studentForm.management_form}}
				{% with studentForm.forms|first as entryForm %}
                                <tr>
                                    <td><label class="KLP_required">Academic Year:</label></td>
                                    <td>                                        
                                        {{entryForm.academic}}
					<input type="hidden" name="form-0-boundary" id="id_boundary" size="15" value="{{extra_context|displayValue:'boundary'}}"/>
					<input type="hidden" name="form-0-student_group" id="id_student_group" size="15" value="{{extra_context|displayValue:'referKey'}}"/>
					<input type="hidden" name="form-0-name" id="id_name" size="15" value=""/>
					<input type="hidden" name="form-0-active" id="id_form-0-active" value="True" />
                                    </td>
				    <td>
                                    	{% for error in entryForm.academic.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
                                </tr>
				{% endwith %}
			    {% endwith %}

                                <tr></tr>
                    		<tr></tr>
                    		<tr></tr>
                    		<tr></tr>
                    		<tr></tr>
                                <tr>
                                    <td>
                                    	<input type="submit" name="save" id="id_save" value="Save" />
                                    </td>
                                    <!--td>
                                    	<input type="submit" name="save_and_continue" id="id_save_and_continue" value="Save And Continue" />
                                    </td>
                                    <td>
                    	    		<input type="submit" name="save_and_create" id="id_save_and_create" value="Save And Create Another" />
      				    </td-->
                                </tr>
				</table>
        </form>
<script>
  $(document).ready(function(){  
  
   $("#id_save").click(function(){
   	$("#id_form-buttonType").val('save');
   	KLP_form_submit();
   });
   
   $("#id_save_and_continue").click(function(){
   	$("#id_form-buttonType").val('save and continue');
   });
   
   $("#id_save_and_create").click(function(){
   	parentVal = $("#id_form-0-parent").val();
   	$("#id_form-buttonType").val('save and add another');
   	KLP_form_submit('id_form-0-parent', parentVal);
   	
   	
   });
    
    
   var KLP_form_submit = function(parentId, parentVal){
   	$.post(
        	$('#url').val(),
        	$("#studentForm").serialize(),
                function(data){
			$("#studEntrForm").html(data);
			var successStatus = $("#success_status").val();
			if (successStatus == 'True'){
				window.parent.tb_remove();
				window.parent.$('#StudentDetail  > tbody:last').append(data);
				window.parent.tb_init('#StudentDetail a.thickbox, area.thickbox, input.thickbox');
				window.parent.$("#stud_Detail").show();
			}
			else{
				
				NFInit();
			}
                    //$("#dyncData").html(data);
                    //NFInit();
                    //if (parentId != null)
                    //	$("#"+parentId).val(parentVal);
               }
           );
   } 

     
   /*$("#schoolForm").submit(function(){
   parentId=$('#id_boundary').val();
    $.post(  
        $('#url').val(),  
        $("#schoolForm").serialize(),  
                function(data){
                    $("#dyncData").html(data);
			ObjId='#boundary_'+parentId
            		Obj=$(ObjId)
                    	call_js(Obj,'school');
               }  
           );  
       });  */
});  
</script>