schools/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from schools.views import *

urlpatterns = patterns('')

utils/urls.py
from django.conf.urls import patterns, url

from .views import set_session
from klprestApi.views.HomeApi import Home

urlpatterns = patterns('',
    url(r'^home/$', Home(), name='home'),
    url(r'^set/session/$', set_session, name='set_session')
)

schools/models.py
import datetime

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from django.db import connection
from django.db.models.signals import post_save, pre_save
from schools.receivers import KLP_NewInst_Permission

from object_permissions import register
from fullhistory import register_model

# Table Structure For Klp

register_model(User)

primary_field_type = [(0, 'Default'),
                      (1, 'Integer'),
                      (2, 'Char'),
                      (3, 'Date'),
                      (4, 'Lookup')]

active_status = [
    (0, 'Deleted'),
    (1, 'Inactive'),
    (2, 'Active'),
    (3, 'Promoted'),
    (4, 'Promotion Failed'),
    (5, 'Passed Out'),
    (6, 'Detained'),
    (7, 'Completed'), ]

INSTITUTION_GENDER = [('boys', 'boys'), ('girls', 'girls'), ('co-ed',
                      'co-ed')]

GENDER = [('male', 'male'), ('female', 'female')]

Group_Type = [('Class', 'Class'), ('Center', 'Center')]

QuestionType = [(1, 'Marks'), (2, 'Grade')]

RELATION_TYPE = [('Mother', 'Mother'),
                 ('Father', 'Father'),
                 ('Siblings', 'Siblings')]

Assessment_type = [(1, 'Institution'), (2, 'Student Group'), (3,
                   'Student')]

alpha_list = [('', 'No Section')]
A_ASCII = 65
Z_ASCII = 90
[alpha_list.append((chr(each), chr(each))) for each in range(A_ASCII, Z_ASCII+1)]


class Institution_Category(models.Model):

    '''This Class stores the Institution Category Information'''

    name = models.CharField(max_length=50)
    category_type = models.IntegerField()

    def __unicode__(self):
        return '%s' % self.name


register_model(Institution_Category)


class Moi_Type(models.Model):

    '''This Class stores the Mother Toungue (Languages) Information'''

    name = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.name


register_model(Moi_Type)


class Institution_Management(models.Model):

    '''This Class stores the Institution Management Information'''

    name = models.CharField(max_length=50)

    def __unicode__(self):
        return '%s' % self.name


register_model(Institution_Management)  # Register model for to store information in fullhistory


class Institution_address(models.Model):

    ''' This class stores information about institution address '''

    address = models.CharField(max_length=1000)
    area = models.CharField(max_length=200, blank=True, null=True)
    pincode = models.CharField(max_length=100, blank=True, null=True)
    landmark = models.CharField(max_length=1000, blank=True, null=True,
                                help_text='Can be comma separated')
    instidentification = \
        models.CharField(max_length=1000, blank=True,
                         null=True,
                         help_text='Can be comma separated')
    instidentification2 = \
        models.CharField(max_length=1000, blank=True,
                         null=True,
                         help_text='Can be comma separated')
    route_information = \
        models.CharField(max_length=500, blank=True,
                         null=True,
                         help_text='Can be comma separated')


register_model(Institution_address)  # Register model for to store information in fullhistory


class Boundary_Category(models.Model):

    '''This Class stores the Boundary Category Information'''

    boundary_category = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s' % self.boundary_category


register_model(Boundary_Category)  # Register model for to store information in fullhistory


class Boundary_Type(models.Model):

    '''This Class stores the Boundary Type Information'''

    boundary_type = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s' % self.boundary_type


register_model(Boundary_Type)  # Register model for to store information in fullhistory


class Staff_Type(models.Model):

    '''This Class stores information about Staff Type'''

    staff_type = models.CharField(max_length=100)
    category_type = models.IntegerField()

    def __unicode__(self):
        return '%s' % self.staff_type


register_model(Staff_Type)  # Register model for to store information in fullhistory


class Staff_Qualifications(models.Model):

    ''' This Class Stores Information about staff qualification '''

    qualification = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s' % self.qualification


register_model(Staff_Qualifications)  # Register model for to store information in fullhistory


class Boundary(models.Model):

    '''This class specifies the longitude and latitute of the area'''

    parent = models.ForeignKey('self', blank=True, null=True)
    name = models.CharField(max_length=300)
    boundary_category = models.ForeignKey(Boundary_Category,
                                          blank=True, null=True)
    boundary_type = models.ForeignKey(Boundary_Type, blank=True,
                                      null=True)
    active = models.IntegerField(blank=True, null=True, default=2)

    class Meta:

        """ Used For ordering """

        ordering = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def getChild(self, boundaryType):
        if Boundary.objects.filter(parent__id=self.id, active=2,
                                   boundary_type=boundaryType).count():
            return True
        elif Institution.objects.filter(boundary__id=self.id,
                                        active=2).count():
            return True
        else:
            return False

    def getModuleName(self):
        return 'boundary'

    def getViewUrl(self, boundaryType):
        return '<a href="/boundary/%s/%s/view/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="Boundary" /> &nbsp; <span id="boundary_%s_text">%s</span> </a>' \
            % (self.id, boundaryType, self.name, self.id, self.name)

    def CreateNewFolder(self, boundaryType):
        return '<span><a href="/boundary/%s/%s/view/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="Boundary" /> &nbsp; <span id="boundary_%s_text">%s</span> </a></span>' \
            % (self.id, boundaryType, self.name, self.id, self.name)

    def get_view_url(self, boundaryType):
        return '/boundary/%s/%s/view/' % (self.id, boundaryType)

    def get_edit_url(self):
        return '/boundary/%s/update/' % self.id

    def get_update_url(self):
        return '/boundary/%d/update/' % self.id

    def getPermissionChild(self, boundaryType):
        if Boundary.objects.filter(parent__id=self.id, active=2,
                                   boundary_type=boundaryType):
            return True
        else:
            return False

    def getPermissionViewUrl(self):
        return '<a href="/boundary/%s/permissions/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
            % (self.id, self.name, self.name)

    def getAssessmentPermissionViewUrl(self, assessment_id):
        return '<a href="/boundary/%s/assessmentpermissions/%s/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
            % (self.id, assessment_id, self.name, self.name)

    def showPermissionViewUrl(self, userSel):
        if self.boundary_category.id in [9, 10, 13, 14]:
            return '<a href="/show/%s/user/%s/permissions/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
                % (self.id, userSel, self.name, self.name)
        else:
            return '<a href="/list/%s/user/%s/permissions/" onclick="return KLP_View(this)" class="KLP_treetxt" title="%s"> <img src="/static_media/tree-images/reicons/boundary.gif" title="boundary" />  %s </a>' \
                % (self.id, userSel, self.name, self.name)


register_model(Boundary)


class Institution(models.Model):

    ''' It stores the all data regarding Institutions'''

    boundary = models.ForeignKey(Boundary)
    dise_code = models.CharField(max_length=14, blank=True, null=True)
    name = models.CharField(max_length=300)
    cat = models.ForeignKey(Institution_Category, blank=True, null=True)
    institution_gender = \
        models.CharField(max_length=10,
                         choices=INSTITUTION_GENDER, default='co-ed')
    languages = models.ManyToManyField(Moi_Type)
    mgmt = models.ForeignKey(Institution_Management, default='ed')
    inst_address = models.ForeignKey(Institution_address, blank=True,
                                     null=True)
    active = models.IntegerField(blank=True, null=True, default=2)

    class Meta:

        ordering = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def get_all_cat(self, category_type):
        return Institution_Category.objects.all(category_type=category_type)

    def getChild(self):
        if StudentGroup.objects.filter(institution__id=self.id,
                                       active=2).count():
            return True
        else:
            return False

    def get_all_mgmt(self):
        return Institution_Management.objects.all()

    def get_all_languages(self):
        return Moi_Type.objects.all()

    def getModuleName(self):
        return 'institution'

    def get_update_url(self):
        return '/institution/%d/update/' % self.id

    def getViewUrl(self):

schools/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# Create your views here.

from django.db import models
from django import forms
from django.forms import ModelForm
from django.db.models import Q
from django.core.context_processors import csrf

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import Template, Context, RequestContext

from models import *
from forms import *

schools/templates/edittemplates/assessment_lookup_call_form.html
{% load template_tags %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{{title}}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
<script language="javascript" type="text/javascript" src="{{ STATIC_URL }}js/niceforms.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/thickbox.js" charset="utf-8"></script>


<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/thickbox.css" charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/form.css" />
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/style.css" />

</head>

<body>
<div id="container">

{% if entry == "Add" %}
<fieldset>
    <legend>{{legend}}</legend>
{% else %}
<div class="tablebg">
{% endif %}

<div id="popData">
<div class="detailHead">
<span class="hedText">Edit Form</span> <span class="KLP_DE_AdStudent"><a href="#" onclick="closeForm()"> Click here to Close </a></span>
</div>
<!-- This to show bulk Students to edit -->
{% for assessment_lookup_id in assessment_lookuplist %}

		<IFRAME SRC="/assessment/{{assessment_id}}/assessment_lookup/{{assessment_lookup_id}}/update/{{forloop.counter}}"
	     		WIDTH=350 HEIGHT=50 style="clear:both;float:none;border:none"
	     		ALIGN=RIGHT
	     	>
		</IFRAME><br/><br/>
{% if forloop.last %}
    <script>
    	$(document).ready(function(){
    		firstIframe = $.find("iframe:first");
    		$(firstIframe).load(function(){
    			setTimeout(function(){
				$('body', $(firstIframe).contents()).find("#id_form-0-first_name").focus();
    		        },200);

    		});

    	});
    </script>
{% endif %}

{% endfor %}

<script>
	function closeForm(){
		window.parent.tb_remove();
	}
</script>
</div>

</body>
</html>

schools/templates/edittemplates/assessment_lookup_form.html
{% load template_tags %}
<style>
body{

padding:0px !important;
}
</style>
<div id="popData">
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
<script language="javascript" type="text/javascript" src="{{ STATIC_URL }}js/niceforms.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/thickbox.js" charset="utf-8"></script>


<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/thickbox.css" charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/form.css" />
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/style.css" />
<form action="." method="POST" enctype="multipart/form-data" id="assessment_lookupForm" onsubmit="return false;" >{% csrf_token %}
          <input type="hidden" name="form-buttonType" id="id_form-buttonType" value="save" />
			    <input type="hidden" id="success_status" size="15" value="{{extra_context|displayValue:'showsuccess'}}" / >
			    <input type="hidden" id="replaceTrue" name="replaceTrue" size="15" value="True" / >

			   <input type="hidden" name="counter" id="id_counter" value="{{extra_context|displayValue:'counter'}}"/>
				 <input type="hidden" id="assessment_id" name="assessment_id" size="15" value="{{extra_context|displayValue:'referKey'}}" / >
				   <input type="hidden" name="url" id="replace_id" value="{{extra_context|displayValue:'assessment_lookup_id'}}" />
				 <input type="hidden" name="url" id="id_lookupUpdateUrl" value="/assessment/{{extra_context|displayValue:'referKey'}}/assessment_lookup/{{extra_context|displayValue:'assessment_lookup_id'}}/update/" />
			    <table class="tblprofile">
				{{form.management_form}}
				{% for entryForm in form.forms %}

				<span style="display:none">{{entryForm.id}} <input type="hidden" id="id_form-0-assessment" name="form-0-assessment" size="15" value="{{extra_context|displayValue:'referKey'}}" / ></span>
		<table>
        		<tr>
      	    			<td>
      		    			<table class="tblprofile">
      						<tr>
      							<td class="rightprofile"><label class="KLP_required">Name</label></td>
      							<td class="rightprofile"><label class="KLP_required">Description</label></td>
								<td>&nbsp;</td>
      						</tr>
      						<tr><td class="leftprofile">
                            					{% render_field entryForm.name 'tabindex=1' %}
                            					<!-- Assessment Name Field -->


                        				<br>
                        					<!-- If Name field has errors show errors -->
                                    				{% for error in entryForm.name.errors %}
	                                				<span class="editErr">{{ error }}</span>
	                                			{% endfor %}
                                    			</td>

      							<td class="leftprofile">
                            					{% render_field entryForm.description 'tabindex=2' %}
                            					<!-- Start Date Field -->
                        				</br>
                        					<!-- If Start Date field has errors show errors -->
                                    				{% for error in entryForm.description.errors %}
	                                				<span class="editErr">{{ error }}</span>
	                                			{% endfor %}
                                    			</td>
												<td>
                                    				<input type="submit" name="save" id="id_save" value="Save" tabindex=4 />
                                    			</td>
      						</tr>




      					</table>
      				</td>
      			</tr>
				  {% endfor %}
    		</table>



</form>
				<script>
  $(document).ready(function(){
     setTimeout(function(){
		$('input:visible:enabled:first').focus();
	},200);

     var KLP_Hide_Msg = function(){
	$("#successMsgHead").hide();
        $("#failureMsgHead").hide();
}

   $("#id_save").click(function(){
        /* Clicking on save button hide all prv msgs and call form submit and pass button type is save */
	KLP_Hide_Msg();

   	KLP_form_submit();
   });



var KLP_form_submit = function(){
    $("#id_save").attr("disabled", "true");

    replaceId =  $('#replace_id').val()
    /* post data using post method */
	assessementId=$('#id_form-0-assessment').val();

	alokupname=$('#id_form-0-name').val();
	alookupdescription=$('#id_form-0-description').val();

    $.post(
        $("#id_lookupUpdateUrl").val(),
        $("#assessment_lookupForm").serialize(),
        function(data){
        	$('#popData').html(data);

		// NFInit();
		$("#id_save").removeAttr("disabled");
		var successStatus = $("#success_status").val();

		if (successStatus == 'True'){
			/* If Success update row */
			$('#assessment_'+assessementId+'_'+replaceId+' .tot-border2', self.parent.parent.document).html(alokupname);
			$('#assessment_'+assessementId+'_'+replaceId+' .tot-border1', self.parent.parent.document).html(alookupdescription);
			window.parent.parent.tb_init('#'+replaceId+' a.thickbox, area.thickbox, input.thickbox');
			window.parent.parent.$("#successMsgHead").show();
	   		window.parent.parent.$("#klp_MsgTxt").html("Assessement Lookup Updated Successfully");
	   		$("body").html("Assessement Lookup Updated Successfully");
        	}
    	});
}
});
</script>

schools/templates/edittemplates/child_form.html
{% load template_tags %}
<div id="popData">
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
<script language="javascript" type="text/javascript" src="{{ STATIC_URL }}js/niceforms.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/thickbox.js" charset="utf-8"></script>


<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/thickbox.css" charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/form.css" />
<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/style.css" />
<form action="." method="POST" enctype="multipart/form-data" id="childForm" onsubmit="return false;" >{% csrf_token %}

			     <input type="hidden" name="url" id="id_StudUpdateUrl" value="/student/{{child.id}}/update/" />
			     <input type="hidden" name="url" id="replace_id" value="{{child.id}}" />

			     <input type="hidden" name="studentgroup" value="{{extra_context|displayValue:'studentgroup_id'}}" id="id_studentgroup" />

                            <input type="hidden" name="form-buttonType" id="id_form-buttonType" value="save" />
			    <input type="hidden" id="school_id" size="15" value="{{extra_context|displayValue:'prevousId'}}" / >
			    <input type="hidden" id="success_status" size="15" value="{{extra_context|displayValue:'showsuccess'}}" / >
			    <input type="hidden" id="replaceTrue" name="replaceTrue" size="15" value="True" / >
			    <input type="hidden" id="mapStudent" name="mapStudent" size="15" value="{{extra_context|displayValue:'mapStudent'}}" / >
			    <input type="hidden" id="assessment_id" name="assessment_id" size="15" value="{{extra_context|displayValue:'assessment_id'}}" / >
			    <table class="tblprofile">
				{{form.management_form}}
				{% for entryForm in form.forms %}

				<tr>
				    <!-- Child Form Headings -->
				    <td align="center"><label class="KLP_required">First Name:</label></td>
				    <td align="center"><label>Middle Name:</label></td>
				    <td align="center"><label>Last Name:</label></td>
				    <td align="center"><label>UID:</label></td>
				    <td align="center"><label>Other Studnet Id:</label></td>
				    <td align="center" style="min-width:200px;max-width:200px"><label class="KLP_required">Date of Birth:</label></td>
				    <td align="center"><label class="KLP_required">Gender:</label></td>
				    <td align="center"><label class="KLP_required">Mother Tongue:</label></td>
				    <td align="center">&nbsp;</td>
				    <td align="center"><label class="KLP_required">Mother First Name:</label></td>
				    <td align="center"><label>Mother Middle Name:</label></td>
				    <td align="center"><label>Mother Last Name:</label></td>
				    <td align="center"><label class="KLP_required">Father First Name:</label></td>
				    <td align="center"><label>Father Middle Name:</label></td>
				    <td align="center"><label>Father Last Name :</label></td>
				    <td align="center">&nbsp;</td>
				</tr>
				<tr>
				    <!-- render all fields for child -->
				    <td align="center">
					{% render_field entryForm.first_name 'tabindex=1' %}
				    </td>
				    <td align="center">
					{% render_field entryForm.middle_name 'tabindex=1' %}
				    </td>
				    <td align="center">
					{% render_field entryForm.last_name 'tabindex=1' %}
				    </td>
				    <td align="center">
					{% render_field entryForm.uid 'tabindex=1' %}
				    </td>
				    <td align="center">
					<input type="text" name="form-0-otherId" id="id_form-0-otherId" value="{% if extra_context|dictValue:'form-0-otherId' %}{{extra_context|dictValue:'form-0-otherId'}}{% else %}{{child.getStudent.other_student_id}}{% endif %}" tabindex=1 size="3"/>
				    </td>
				    <td align="center" style="min-width:200px;max-width:200px">
					{% render_field entryForm.dob 'tabindex=1' %}
				    </td>
				    <td align="center">
					{% render_field entryForm.gender 'tabindex=1' %}
				    </td>
				    <td align="center">
					{% render_field entryForm.mt 'tabindex=1' %}
					<input type="hidden" name="form-0-child" id="id_child" size="15" value="{% if extra_context|dictValue:'form-0-otherId' %}{{extra_context|dictValue:'form-0-otherId'}} {% else %} {{child.getStudent.other_student_id}} {% endif %}"/>
					<input type="hidden" name="form-0-boundary" id="id_boundary" size="15" value="{{extra_context|displayValue:'referKey'}}"/>
					<input type="hidden" name="form-0-active" id="id_active" size="15" value="2"/>
					<input type="hidden" name="ModelName" id = "model" value="{{extra_context|displayValue:'modelName'}}" />
				    </td>
				    <td align="center">&nbsp;</td>
				    <td align="center">
					<input type="text" name = "form-0-motherfirstname" id="id_form-0-motherfirstname" value="{% if extra_context|dictValue:'form-0-motherfirstname' %}{{extra_context|dictValue:'form-0-motherfirstname'}}{% else %}{{child.getMother.first_name}}{% endif %}" tabindex='1' size=8/>
				    </td>
				    <td align="center">
					<input type="text" name = "form-0-mothermiddlename" id="id_form-0-mothermiddlename" value="{% if extra_context|dictValue:'form-0-mothermiddlename' %}{{extra_context|dictValue:'form-0-mothermiddlename'}}{% else %}{{child.getMother.middle_name}}{% endif %}" tabindex='1' size=8/>
				    </td>
				    <td align="center">
					<input type="text" name = "form-0-motherlastname" id="id_form-0-motherlastname" value="{% if extra_context|dictValue:'form-0-motherlastname' %}{{extra_context|dictValue:'form-0-motherlastname'}}{% else %}{{child.getMother.last_name}}{% endif %}" tabindex='1' size=8/>
				    </td>
				    <td align="center">
					<input type="text" name = "form-0-fatherfirstname" id="id_form-0-fatherfirstname" value="{% if extra_context|dictValue:'form-0-fatherfirstname' %}{{extra_context|dictValue:'form-0-fatherfirstname'}}{% else %}{{child.getFather.first_name}}{% endif %}" tabindex='1' size=8/>

				    </td>
				    <td align="center">
					<input type="text" name = "form-0-fathermiddlename" id="id_form-0-fathermiddlename" value="{% if extra_context|dictValue:'form-0-fathermiddlename' %}{{extra_context|dictValue:'form-0-fathermiddlename'}}{% else %}{{child.getFather.middle_name}}{% endif %}" tabindex='1' size=8/>

				    </td>
				    <td align="center">
					<input type="text" name = "form-0-fatherlastname" id="id_form-0-fatherlastname" value="{% if extra_context|dictValue:'form-0-fatherlastname' %}{{extra_context|dictValue:'form-0-fatherlastname'}}{% else %}{{child.getFather.last_name}}{% endif %}" tabindex='1' size=8/>

				    </td>
				    <td align="center">
				    	<input type="hidden" name="counter" id="id_counter" value="{{extra_context|displayValue:'counter'}}"/>
				    	<span style="display:none">{{entryForm.id}}</span>
                                    	<input type="submit" name="save" id="id_save" value="Save" tabindex="1"/>
                                    </td>
				</tr>
				<tr>
				   <!-- Show error msgs if field id not valid -->
				   <td align="center">
                                    	{% for error in entryForm.first_name.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
				    <td align="center">
                                    	{% for error in entryForm.middle_name.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>

				    <td align="center">
                                    	{% for error in entryForm.last_name.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
                                    <td align="center">
                                    	{% for error in entryForm.uid.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
                                    <td align="center">&nbsp;</td>
                                    <td align="center">
                                    	{% for error in entryForm.dob.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
                                    <td align="center">
                                    	{% for error in entryForm.gender.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
                                    <td align="center">
                                    	{% for error in entryForm.mt.errors %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>
                                    <td align="center">&nbsp;</td>
                                    <td align="center" colspan="5">
                                    	{% for error in entryForm.errors.fatherfirstname %}
	                                	<span class="editErr">{{ error }}</span>
	                                {% endfor %}
                                    </td>

                                    <td align="center">&nbsp;</td>
				</tr>



				{% endfor %}

				</table>
				<script>
  $(document).ready(function(){
     setTimeout(function(){
		$('input:visible:enabled:first').focus();
	},200);

     var KLP_Hide_Msg = function(){
	$("#successMsgHead").hide();
        $("#failureMsgHead").hide();
}

   $("#id_save").click(function(){
        /* Clicking on save button hide all prv msgs and call form submit and pass button type is save */
	KLP_Hide_Msg();
	parentVal = $("#id_boundary").val();
   	$("#id_form-buttonType").val('save');
   	KLP_form_submit(parentVal,'id_boundary');
   });



var KLP_form_submit = function(parentVal, parentId){
    $("#id_save").attr("disabled", "true");
    modelName=$('#model').val();
    replaceId =  'student_'+$('#replace_id').val()
    /* post data using post method */
    $.post(
        $("#id_StudUpdateUrl").val(),
        $("#childForm").serialize(),
        function(data){
        	$('#popData').html(data);
		// NFInit();
		$("#id_save").removeAttr("disabled");
		var successStatus = $("#success_status").val();
		if (successStatus == 'True'){
			/* If Success update row */
			$('#'+replaceId, self.parent.parent.document).replaceWith(data);
			window.parent.parent.tb_init('#'+replaceId+' a.thickbox, area.thickbox, input.thickbox');
			window.parent.parent.$("#successMsgHead").show();
	   		window.parent.parent.$("#klp_MsgTxt").html("Student Updated Successfully");
	   		$("body").html("Student Updated Successfully");
        	}
    	});
}
});
</script>
        </form>
        </div>